repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: (\.(svg|png|pdf)$)|(CODE_OF_CONDUCT.md)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        # args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
      - id: numpydoc-validation
        exclude: (__init__.py|tests/.*|docs/.*)

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: ^(tests|docs)/.*

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.4.3
    hooks:
      - id: pyproject-fmt
        args: [--keep-full-version, --no-print-diff]
